
namespace projet_fames
{
    partial class frmlogin
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmlogin));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Utilities.BunifuPages.BunifuAnimatorNS.Animation animation1 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.pnlmenu = new System.Windows.Forms.Panel();
            this.btncreeationcompte = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.piclogo = new System.Windows.Forms.PictureBox();
            this.btnidentification = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.bunifuPages1 = new Bunifu.UI.WinForms.BunifuPages();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.txtmdp = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtnom = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.lbltitre = new System.Windows.Forms.Label();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.txtmdp2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtemail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtnom2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btncreation = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.lbltitre2 = new System.Windows.Forms.Label();
            this.chbmdp = new System.Windows.Forms.CheckBox();
            this.pnlmenu.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.piclogo)).BeginInit();
            this.bunifuPages1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.SuspendLayout();
            // 
            // pnlmenu
            // 
            this.pnlmenu.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(173)))), ((int)(((byte)(164)))));
            this.pnlmenu.Controls.Add(this.btncreeationcompte);
            this.pnlmenu.Controls.Add(this.piclogo);
            this.pnlmenu.Controls.Add(this.btnidentification);
            this.pnlmenu.Dock = System.Windows.Forms.DockStyle.Left;
            this.pnlmenu.Location = new System.Drawing.Point(0, 0);
            this.pnlmenu.Name = "pnlmenu";
            this.pnlmenu.Size = new System.Drawing.Size(300, 457);
            this.pnlmenu.TabIndex = 0;
            // 
            // btncreeationcompte
            // 
            this.btncreeationcompte.AllowAnimations = true;
            this.btncreeationcompte.AllowMouseEffects = true;
            this.btncreeationcompte.AllowToggling = false;
            this.btncreeationcompte.AnimationSpeed = 200;
            this.btncreeationcompte.AutoGenerateColors = false;
            this.btncreeationcompte.AutoRoundBorders = false;
            this.btncreeationcompte.AutoSizeLeftIcon = true;
            this.btncreeationcompte.AutoSizeRightIcon = true;
            this.btncreeationcompte.BackColor = System.Drawing.Color.Transparent;
            this.btncreeationcompte.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btncreeationcompte.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btncreeationcompte.BackgroundImage")));
            this.btncreeationcompte.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btncreeationcompte.ButtonText = "CREATION DE COMPTE";
            this.btncreeationcompte.ButtonTextMarginLeft = 0;
            this.btncreeationcompte.ColorContrastOnClick = 45;
            this.btncreeationcompte.ColorContrastOnHover = 45;
            this.btncreeationcompte.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btncreeationcompte.CustomizableEdges = borderEdges1;
            this.btncreeationcompte.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btncreeationcompte.DisabledBorderColor = System.Drawing.Color.WhiteSmoke;
            this.btncreeationcompte.DisabledFillColor = System.Drawing.Color.WhiteSmoke;
            this.btncreeationcompte.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.btncreeationcompte.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btncreeationcompte.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btncreeationcompte.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btncreeationcompte.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btncreeationcompte.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btncreeationcompte.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btncreeationcompte.IconMarginLeft = 11;
            this.btncreeationcompte.IconPadding = 10;
            this.btncreeationcompte.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btncreeationcompte.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btncreeationcompte.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btncreeationcompte.IconSize = 25;
            this.btncreeationcompte.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btncreeationcompte.IdleBorderRadius = 35;
            this.btncreeationcompte.IdleBorderThickness = 2;
            this.btncreeationcompte.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btncreeationcompte.IdleIconLeftImage = null;
            this.btncreeationcompte.IdleIconRightImage = null;
            this.btncreeationcompte.IndicateFocus = false;
            this.btncreeationcompte.Location = new System.Drawing.Point(35, 389);
            this.btncreeationcompte.Name = "btncreeationcompte";
            this.btncreeationcompte.OnDisabledState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btncreeationcompte.OnDisabledState.BorderRadius = 35;
            this.btncreeationcompte.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btncreeationcompte.OnDisabledState.BorderThickness = 2;
            this.btncreeationcompte.OnDisabledState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btncreeationcompte.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.btncreeationcompte.OnDisabledState.IconLeftImage = null;
            this.btncreeationcompte.OnDisabledState.IconRightImage = null;
            this.btncreeationcompte.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btncreeationcompte.onHoverState.BorderRadius = 35;
            this.btncreeationcompte.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btncreeationcompte.onHoverState.BorderThickness = 2;
            this.btncreeationcompte.onHoverState.FillColor = System.Drawing.Color.White;
            this.btncreeationcompte.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.btncreeationcompte.onHoverState.IconLeftImage = null;
            this.btncreeationcompte.onHoverState.IconRightImage = null;
            this.btncreeationcompte.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btncreeationcompte.OnIdleState.BorderRadius = 35;
            this.btncreeationcompte.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btncreeationcompte.OnIdleState.BorderThickness = 2;
            this.btncreeationcompte.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btncreeationcompte.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btncreeationcompte.OnIdleState.IconLeftImage = null;
            this.btncreeationcompte.OnIdleState.IconRightImage = null;
            this.btncreeationcompte.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btncreeationcompte.OnPressedState.BorderRadius = 35;
            this.btncreeationcompte.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btncreeationcompte.OnPressedState.BorderThickness = 2;
            this.btncreeationcompte.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btncreeationcompte.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btncreeationcompte.OnPressedState.IconLeftImage = null;
            this.btncreeationcompte.OnPressedState.IconRightImage = null;
            this.btncreeationcompte.Size = new System.Drawing.Size(230, 54);
            this.btncreeationcompte.TabIndex = 2;
            this.btncreeationcompte.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btncreeationcompte.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btncreeationcompte.TextMarginLeft = 0;
            this.btncreeationcompte.TextPadding = new System.Windows.Forms.Padding(0);
            this.btncreeationcompte.UseDefaultRadiusAndThickness = true;
            this.btncreeationcompte.Click += new System.EventHandler(this.btncreeationcompte_Click);
            // 
            // piclogo
            // 
            this.piclogo.Image = global::projet_fames.Properties.Resources.logofrv;
            this.piclogo.Location = new System.Drawing.Point(71, 71);
            this.piclogo.Name = "piclogo";
            this.piclogo.Size = new System.Drawing.Size(175, 137);
            this.piclogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.piclogo.TabIndex = 1;
            this.piclogo.TabStop = false;
            // 
            // btnidentification
            // 
            this.btnidentification.AllowAnimations = true;
            this.btnidentification.AllowMouseEffects = true;
            this.btnidentification.AllowToggling = false;
            this.btnidentification.AnimationSpeed = 200;
            this.btnidentification.AutoGenerateColors = false;
            this.btnidentification.AutoRoundBorders = false;
            this.btnidentification.AutoSizeLeftIcon = true;
            this.btnidentification.AutoSizeRightIcon = true;
            this.btnidentification.BackColor = System.Drawing.Color.Transparent;
            this.btnidentification.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnidentification.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnidentification.BackgroundImage")));
            this.btnidentification.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnidentification.ButtonText = "S\'IDENTIFIER";
            this.btnidentification.ButtonTextMarginLeft = 0;
            this.btnidentification.ColorContrastOnClick = 45;
            this.btnidentification.ColorContrastOnHover = 45;
            this.btnidentification.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnidentification.CustomizableEdges = borderEdges2;
            this.btnidentification.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnidentification.DisabledBorderColor = System.Drawing.Color.WhiteSmoke;
            this.btnidentification.DisabledFillColor = System.Drawing.Color.WhiteSmoke;
            this.btnidentification.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.btnidentification.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnidentification.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnidentification.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnidentification.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnidentification.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnidentification.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnidentification.IconMarginLeft = 11;
            this.btnidentification.IconPadding = 10;
            this.btnidentification.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnidentification.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnidentification.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnidentification.IconSize = 25;
            this.btnidentification.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnidentification.IdleBorderRadius = 35;
            this.btnidentification.IdleBorderThickness = 2;
            this.btnidentification.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnidentification.IdleIconLeftImage = null;
            this.btnidentification.IdleIconRightImage = null;
            this.btnidentification.IndicateFocus = false;
            this.btnidentification.Location = new System.Drawing.Point(62, 329);
            this.btnidentification.Name = "btnidentification";
            this.btnidentification.OnDisabledState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btnidentification.OnDisabledState.BorderRadius = 35;
            this.btnidentification.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnidentification.OnDisabledState.BorderThickness = 2;
            this.btnidentification.OnDisabledState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnidentification.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.btnidentification.OnDisabledState.IconLeftImage = null;
            this.btnidentification.OnDisabledState.IconRightImage = null;
            this.btnidentification.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnidentification.onHoverState.BorderRadius = 35;
            this.btnidentification.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnidentification.onHoverState.BorderThickness = 2;
            this.btnidentification.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnidentification.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.btnidentification.onHoverState.IconLeftImage = null;
            this.btnidentification.onHoverState.IconRightImage = null;
            this.btnidentification.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnidentification.OnIdleState.BorderRadius = 35;
            this.btnidentification.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnidentification.OnIdleState.BorderThickness = 2;
            this.btnidentification.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnidentification.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnidentification.OnIdleState.IconLeftImage = null;
            this.btnidentification.OnIdleState.IconRightImage = null;
            this.btnidentification.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnidentification.OnPressedState.BorderRadius = 35;
            this.btnidentification.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnidentification.OnPressedState.BorderThickness = 2;
            this.btnidentification.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnidentification.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnidentification.OnPressedState.IconLeftImage = null;
            this.btnidentification.OnPressedState.IconRightImage = null;
            this.btnidentification.Size = new System.Drawing.Size(175, 54);
            this.btnidentification.TabIndex = 0;
            this.btnidentification.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnidentification.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnidentification.TextMarginLeft = 0;
            this.btnidentification.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnidentification.UseDefaultRadiusAndThickness = true;
            this.btnidentification.Click += new System.EventHandler(this.btnidentification_Click);
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = false;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = false;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // bunifuPages1
            // 
            this.bunifuPages1.Alignment = System.Windows.Forms.TabAlignment.Bottom;
            this.bunifuPages1.AllowTransitions = false;
            this.bunifuPages1.Controls.Add(this.tabPage1);
            this.bunifuPages1.Controls.Add(this.tabPage2);
            this.bunifuPages1.Location = new System.Drawing.Point(306, 12);
            this.bunifuPages1.Multiline = true;
            this.bunifuPages1.Name = "bunifuPages1";
            this.bunifuPages1.Page = this.tabPage1;
            this.bunifuPages1.PageIndex = 0;
            this.bunifuPages1.PageName = "tabPage1";
            this.bunifuPages1.PageTitle = "IDENTIFICATION";
            this.bunifuPages1.SelectedIndex = 0;
            this.bunifuPages1.Size = new System.Drawing.Size(617, 417);
            this.bunifuPages1.TabIndex = 1;
            animation1.AnimateOnlyDifferences = true;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.bunifuPages1.Transition = animation1;
            this.bunifuPages1.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.Scale;
            // 
            // tabPage1
            // 
            this.tabPage1.BackColor = System.Drawing.SystemColors.Control;
            this.tabPage1.Controls.Add(this.chbmdp);
            this.tabPage1.Controls.Add(this.txtmdp);
            this.tabPage1.Controls.Add(this.txtnom);
            this.tabPage1.Controls.Add(this.bunifuButton21);
            this.tabPage1.Controls.Add(this.lbltitre);
            this.tabPage1.Location = new System.Drawing.Point(4, 4);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(609, 384);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "IDENTIFICATION";
            // 
            // txtmdp
            // 
            this.txtmdp.AcceptsReturn = false;
            this.txtmdp.AcceptsTab = false;
            this.txtmdp.AnimationSpeed = 200;
            this.txtmdp.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtmdp.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtmdp.AutoSizeHeight = true;
            this.txtmdp.BackColor = System.Drawing.Color.Transparent;
            this.txtmdp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtmdp.BackgroundImage")));
            this.txtmdp.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.txtmdp.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtmdp.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            this.txtmdp.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtmdp.BorderRadius = 1;
            this.txtmdp.BorderThickness = 1;
            this.txtmdp.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtmdp.Cursor = System.Windows.Forms.Cursors.WaitCursor;
            this.txtmdp.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtmdp.DefaultText = "";
            this.txtmdp.FillColor = System.Drawing.Color.White;
            this.txtmdp.HideSelection = true;
            this.txtmdp.IconLeft = global::projet_fames.Properties.Resources.password;
            this.txtmdp.IconLeftCursor = System.Windows.Forms.Cursors.WaitCursor;
            this.txtmdp.IconPadding = 5;
            this.txtmdp.IconRight = null;
            this.txtmdp.IconRightCursor = System.Windows.Forms.Cursors.WaitCursor;
            this.txtmdp.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.txtmdp.Lines = new string[0];
            this.txtmdp.Location = new System.Drawing.Point(116, 173);
            this.txtmdp.MaxLength = 32767;
            this.txtmdp.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtmdp.Modified = false;
            this.txtmdp.Multiline = false;
            this.txtmdp.Name = "txtmdp";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtmdp.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtmdp.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtmdp.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtmdp.OnIdleState = stateProperties4;
            this.txtmdp.Padding = new System.Windows.Forms.Padding(3);
            this.txtmdp.PasswordChar = '\0';
            this.txtmdp.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtmdp.PlaceholderText = "MOT DE PASSE";
            this.txtmdp.ReadOnly = false;
            this.txtmdp.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtmdp.SelectedText = "";
            this.txtmdp.SelectionLength = 0;
            this.txtmdp.SelectionStart = 0;
            this.txtmdp.ShortcutsEnabled = true;
            this.txtmdp.Size = new System.Drawing.Size(375, 46);
            this.txtmdp.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtmdp.TabIndex = 8;
            this.txtmdp.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtmdp.TextMarginBottom = 0;
            this.txtmdp.TextMarginLeft = 7;
            this.txtmdp.TextMarginTop = 1;
            this.txtmdp.TextPlaceholder = "MOT DE PASSE";
            this.txtmdp.UseSystemPasswordChar = false;
            this.txtmdp.UseWaitCursor = true;
            this.txtmdp.WordWrap = true;
            this.txtmdp.TextChange += new System.EventHandler(this.txtmdp_TextChange);
            // 
            // txtnom
            // 
            this.txtnom.AcceptsReturn = false;
            this.txtnom.AcceptsTab = false;
            this.txtnom.AnimationSpeed = 200;
            this.txtnom.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtnom.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtnom.AutoSizeHeight = true;
            this.txtnom.BackColor = System.Drawing.Color.Transparent;
            this.txtnom.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtnom.BackgroundImage")));
            this.txtnom.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.txtnom.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtnom.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            this.txtnom.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtnom.BorderRadius = 1;
            this.txtnom.BorderThickness = 1;
            this.txtnom.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtnom.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnom.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtnom.DefaultText = "";
            this.txtnom.FillColor = System.Drawing.Color.White;
            this.txtnom.HideSelection = true;
            this.txtnom.IconLeft = global::projet_fames.Properties.Resources.user;
            this.txtnom.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnom.IconPadding = 5;
            this.txtnom.IconRight = null;
            this.txtnom.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnom.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.txtnom.Lines = new string[0];
            this.txtnom.Location = new System.Drawing.Point(117, 98);
            this.txtnom.MaxLength = 32767;
            this.txtnom.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtnom.Modified = false;
            this.txtnom.Multiline = false;
            this.txtnom.Name = "txtnom";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnom.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtnom.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnom.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnom.OnIdleState = stateProperties8;
            this.txtnom.Padding = new System.Windows.Forms.Padding(3);
            this.txtnom.PasswordChar = '\0';
            this.txtnom.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtnom.PlaceholderText = "NOM D\'UTILISATEUR";
            this.txtnom.ReadOnly = false;
            this.txtnom.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtnom.SelectedText = "";
            this.txtnom.SelectionLength = 0;
            this.txtnom.SelectionStart = 0;
            this.txtnom.ShortcutsEnabled = true;
            this.txtnom.Size = new System.Drawing.Size(375, 46);
            this.txtnom.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtnom.TabIndex = 7;
            this.txtnom.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtnom.TextMarginBottom = 0;
            this.txtnom.TextMarginLeft = 7;
            this.txtnom.TextMarginTop = 1;
            this.txtnom.TextPlaceholder = "NOM D\'UTILISATEUR";
            this.txtnom.UseSystemPasswordChar = false;
            this.txtnom.WordWrap = true;
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "S\'IDENTIFIER";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges3;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton21.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton21.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.bunifuButton21.IdleBorderRadius = 35;
            this.bunifuButton21.IdleBorderThickness = 2;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(216, 286);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 35;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 2;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.bunifuButton21.onHoverState.BorderRadius = 35;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 2;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.bunifuButton21.OnIdleState.BorderRadius = 35;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 2;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.BorderRadius = 35;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 2;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(175, 54);
            this.bunifuButton21.TabIndex = 6;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            // 
            // lbltitre
            // 
            this.lbltitre.AutoSize = true;
            this.lbltitre.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbltitre.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.lbltitre.Location = new System.Drawing.Point(209, 15);
            this.lbltitre.Name = "lbltitre";
            this.lbltitre.Size = new System.Drawing.Size(190, 38);
            this.lbltitre.TabIndex = 0;
            this.lbltitre.Text = "S\'IDENTIFIER";
            // 
            // tabPage2
            // 
            this.tabPage2.BackColor = System.Drawing.SystemColors.Control;
            this.tabPage2.Controls.Add(this.txtmdp2);
            this.tabPage2.Controls.Add(this.txtemail);
            this.tabPage2.Controls.Add(this.txtnom2);
            this.tabPage2.Controls.Add(this.btncreation);
            this.tabPage2.Controls.Add(this.lbltitre2);
            this.tabPage2.Location = new System.Drawing.Point(4, 4);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(609, 384);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "CREATION";
            // 
            // txtmdp2
            // 
            this.txtmdp2.AcceptsReturn = false;
            this.txtmdp2.AcceptsTab = false;
            this.txtmdp2.AnimationSpeed = 200;
            this.txtmdp2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtmdp2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtmdp2.AutoSizeHeight = true;
            this.txtmdp2.BackColor = System.Drawing.Color.Transparent;
            this.txtmdp2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtmdp2.BackgroundImage")));
            this.txtmdp2.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.txtmdp2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtmdp2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            this.txtmdp2.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtmdp2.BorderRadius = 1;
            this.txtmdp2.BorderThickness = 1;
            this.txtmdp2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtmdp2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtmdp2.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtmdp2.DefaultText = "";
            this.txtmdp2.FillColor = System.Drawing.Color.White;
            this.txtmdp2.HideSelection = true;
            this.txtmdp2.IconLeft = global::projet_fames.Properties.Resources.password;
            this.txtmdp2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtmdp2.IconPadding = 5;
            this.txtmdp2.IconRight = null;
            this.txtmdp2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtmdp2.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.txtmdp2.Lines = new string[0];
            this.txtmdp2.Location = new System.Drawing.Point(132, 226);
            this.txtmdp2.MaxLength = 32767;
            this.txtmdp2.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtmdp2.Modified = false;
            this.txtmdp2.Multiline = false;
            this.txtmdp2.Name = "txtmdp2";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtmdp2.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtmdp2.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtmdp2.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtmdp2.OnIdleState = stateProperties12;
            this.txtmdp2.Padding = new System.Windows.Forms.Padding(3);
            this.txtmdp2.PasswordChar = '\0';
            this.txtmdp2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtmdp2.PlaceholderText = "MOT DE PASSE";
            this.txtmdp2.ReadOnly = false;
            this.txtmdp2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtmdp2.SelectedText = "";
            this.txtmdp2.SelectionLength = 0;
            this.txtmdp2.SelectionStart = 0;
            this.txtmdp2.ShortcutsEnabled = true;
            this.txtmdp2.Size = new System.Drawing.Size(375, 46);
            this.txtmdp2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtmdp2.TabIndex = 12;
            this.txtmdp2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtmdp2.TextMarginBottom = 0;
            this.txtmdp2.TextMarginLeft = 7;
            this.txtmdp2.TextMarginTop = 1;
            this.txtmdp2.TextPlaceholder = "MOT DE PASSE";
            this.txtmdp2.UseSystemPasswordChar = false;
            this.txtmdp2.WordWrap = true;
            // 
            // txtemail
            // 
            this.txtemail.AcceptsReturn = false;
            this.txtemail.AcceptsTab = false;
            this.txtemail.AnimationSpeed = 200;
            this.txtemail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtemail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtemail.AutoSizeHeight = true;
            this.txtemail.BackColor = System.Drawing.Color.Transparent;
            this.txtemail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtemail.BackgroundImage")));
            this.txtemail.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.txtemail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtemail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            this.txtemail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtemail.BorderRadius = 1;
            this.txtemail.BorderThickness = 1;
            this.txtemail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtemail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtemail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtemail.DefaultText = "";
            this.txtemail.FillColor = System.Drawing.Color.White;
            this.txtemail.HideSelection = true;
            this.txtemail.IconLeft = global::projet_fames.Properties.Resources.email;
            this.txtemail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtemail.IconPadding = 5;
            this.txtemail.IconRight = null;
            this.txtemail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtemail.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.txtemail.Lines = new string[0];
            this.txtemail.Location = new System.Drawing.Point(132, 150);
            this.txtemail.MaxLength = 32767;
            this.txtemail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtemail.Modified = false;
            this.txtemail.Multiline = false;
            this.txtemail.Name = "txtemail";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtemail.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtemail.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtemail.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtemail.OnIdleState = stateProperties16;
            this.txtemail.Padding = new System.Windows.Forms.Padding(3);
            this.txtemail.PasswordChar = '\0';
            this.txtemail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtemail.PlaceholderText = "EMAIL";
            this.txtemail.ReadOnly = false;
            this.txtemail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtemail.SelectedText = "";
            this.txtemail.SelectionLength = 0;
            this.txtemail.SelectionStart = 0;
            this.txtemail.ShortcutsEnabled = true;
            this.txtemail.Size = new System.Drawing.Size(375, 46);
            this.txtemail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtemail.TabIndex = 11;
            this.txtemail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtemail.TextMarginBottom = 0;
            this.txtemail.TextMarginLeft = 7;
            this.txtemail.TextMarginTop = 1;
            this.txtemail.TextPlaceholder = "EMAIL";
            this.txtemail.UseSystemPasswordChar = false;
            this.txtemail.WordWrap = true;
            // 
            // txtnom2
            // 
            this.txtnom2.AcceptsReturn = false;
            this.txtnom2.AcceptsTab = false;
            this.txtnom2.AnimationSpeed = 200;
            this.txtnom2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtnom2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtnom2.AutoSizeHeight = true;
            this.txtnom2.BackColor = System.Drawing.Color.Transparent;
            this.txtnom2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtnom2.BackgroundImage")));
            this.txtnom2.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.txtnom2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtnom2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            this.txtnom2.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtnom2.BorderRadius = 1;
            this.txtnom2.BorderThickness = 1;
            this.txtnom2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtnom2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnom2.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtnom2.DefaultText = "";
            this.txtnom2.FillColor = System.Drawing.Color.White;
            this.txtnom2.HideSelection = true;
            this.txtnom2.IconLeft = global::projet_fames.Properties.Resources.user;
            this.txtnom2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnom2.IconPadding = 5;
            this.txtnom2.IconRight = null;
            this.txtnom2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnom2.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.txtnom2.Lines = new string[0];
            this.txtnom2.Location = new System.Drawing.Point(132, 74);
            this.txtnom2.MaxLength = 32767;
            this.txtnom2.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtnom2.Modified = false;
            this.txtnom2.Multiline = false;
            this.txtnom2.Name = "txtnom2";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnom2.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtnom2.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnom2.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnom2.OnIdleState = stateProperties20;
            this.txtnom2.Padding = new System.Windows.Forms.Padding(3);
            this.txtnom2.PasswordChar = '\0';
            this.txtnom2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtnom2.PlaceholderText = "NOM D\'UTILISATEUR";
            this.txtnom2.ReadOnly = false;
            this.txtnom2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtnom2.SelectedText = "";
            this.txtnom2.SelectionLength = 0;
            this.txtnom2.SelectionStart = 0;
            this.txtnom2.ShortcutsEnabled = true;
            this.txtnom2.Size = new System.Drawing.Size(375, 46);
            this.txtnom2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtnom2.TabIndex = 10;
            this.txtnom2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtnom2.TextMarginBottom = 0;
            this.txtnom2.TextMarginLeft = 7;
            this.txtnom2.TextMarginTop = 1;
            this.txtnom2.TextPlaceholder = "NOM D\'UTILISATEUR";
            this.txtnom2.UseSystemPasswordChar = false;
            this.txtnom2.WordWrap = true;
            // 
            // btncreation
            // 
            this.btncreation.AllowAnimations = true;
            this.btncreation.AllowMouseEffects = true;
            this.btncreation.AllowToggling = false;
            this.btncreation.AnimationSpeed = 200;
            this.btncreation.AutoGenerateColors = false;
            this.btncreation.AutoRoundBorders = false;
            this.btncreation.AutoSizeLeftIcon = true;
            this.btncreation.AutoSizeRightIcon = true;
            this.btncreation.BackColor = System.Drawing.Color.Transparent;
            this.btncreation.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.btncreation.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btncreation.BackgroundImage")));
            this.btncreation.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btncreation.ButtonText = "VALIDER";
            this.btncreation.ButtonTextMarginLeft = 0;
            this.btncreation.ColorContrastOnClick = 45;
            this.btncreation.ColorContrastOnHover = 45;
            this.btncreation.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btncreation.CustomizableEdges = borderEdges4;
            this.btncreation.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btncreation.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            this.btncreation.DisabledFillColor = System.Drawing.Color.WhiteSmoke;
            this.btncreation.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            this.btncreation.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btncreation.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btncreation.ForeColor = System.Drawing.Color.White;
            this.btncreation.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btncreation.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btncreation.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btncreation.IconMarginLeft = 11;
            this.btncreation.IconPadding = 10;
            this.btncreation.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btncreation.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btncreation.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btncreation.IconSize = 25;
            this.btncreation.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.btncreation.IdleBorderRadius = 35;
            this.btncreation.IdleBorderThickness = 2;
            this.btncreation.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.btncreation.IdleIconLeftImage = null;
            this.btncreation.IdleIconRightImage = null;
            this.btncreation.IndicateFocus = false;
            this.btncreation.Location = new System.Drawing.Point(428, 327);
            this.btncreation.Name = "btncreation";
            this.btncreation.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            this.btncreation.OnDisabledState.BorderRadius = 35;
            this.btncreation.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btncreation.OnDisabledState.BorderThickness = 2;
            this.btncreation.OnDisabledState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btncreation.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(116)))), ((int)(((byte)(109)))));
            this.btncreation.OnDisabledState.IconLeftImage = null;
            this.btncreation.OnDisabledState.IconRightImage = null;
            this.btncreation.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.btncreation.onHoverState.BorderRadius = 35;
            this.btncreation.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btncreation.onHoverState.BorderThickness = 2;
            this.btncreation.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btncreation.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.btncreation.onHoverState.IconLeftImage = null;
            this.btncreation.onHoverState.IconRightImage = null;
            this.btncreation.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.btncreation.OnIdleState.BorderRadius = 35;
            this.btncreation.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btncreation.OnIdleState.BorderThickness = 2;
            this.btncreation.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.btncreation.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btncreation.OnIdleState.IconLeftImage = null;
            this.btncreation.OnIdleState.IconRightImage = null;
            this.btncreation.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btncreation.OnPressedState.BorderRadius = 35;
            this.btncreation.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btncreation.OnPressedState.BorderThickness = 2;
            this.btncreation.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btncreation.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btncreation.OnPressedState.IconLeftImage = null;
            this.btncreation.OnPressedState.IconRightImage = null;
            this.btncreation.Size = new System.Drawing.Size(175, 54);
            this.btncreation.TabIndex = 7;
            this.btncreation.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btncreation.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btncreation.TextMarginLeft = 0;
            this.btncreation.TextPadding = new System.Windows.Forms.Padding(0);
            this.btncreation.UseDefaultRadiusAndThickness = true;
            // 
            // lbltitre2
            // 
            this.lbltitre2.AutoSize = true;
            this.lbltitre2.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbltitre2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(182)))), ((int)(((byte)(148)))));
            this.lbltitre2.Location = new System.Drawing.Point(145, 14);
            this.lbltitre2.Name = "lbltitre2";
            this.lbltitre2.Size = new System.Drawing.Size(318, 38);
            this.lbltitre2.TabIndex = 3;
            this.lbltitre2.Text = "CREATION DE COMPTE";
            // 
            // chbmdp
            // 
            this.chbmdp.AutoSize = true;
            this.chbmdp.Font = new System.Drawing.Font("Microsoft YaHei", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chbmdp.ForeColor = System.Drawing.Color.Firebrick;
            this.chbmdp.Location = new System.Drawing.Point(308, 237);
            this.chbmdp.Name = "chbmdp";
            this.chbmdp.Size = new System.Drawing.Size(295, 29);
            this.chbmdp.TabIndex = 2;
            this.chbmdp.Text = "AFFICHER LE MOT DE PASSE";
            this.chbmdp.UseVisualStyleBackColor = true;
            this.chbmdp.CheckedChanged += new System.EventHandler(this.chbmdp_CheckedChanged);
            // 
            // frmlogin
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(935, 457);
            this.Controls.Add(this.bunifuPages1);
            this.Controls.Add(this.pnlmenu);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmlogin";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmlogin";
            this.Load += new System.EventHandler(this.frmlogin_Load);
            this.pnlmenu.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.piclogo)).EndInit();
            this.bunifuPages1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel pnlmenu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnidentification;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private System.Windows.Forms.PictureBox piclogo;
        private Bunifu.UI.WinForms.BunifuPages bunifuPages1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.Label lbltitre;
        private System.Windows.Forms.Label lbltitre2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btncreeationcompte;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btncreation;
        private Bunifu.UI.WinForms.BunifuTextBox txtmdp;
        private Bunifu.UI.WinForms.BunifuTextBox txtnom;
        private Bunifu.UI.WinForms.BunifuTextBox txtmdp2;
        private Bunifu.UI.WinForms.BunifuTextBox txtemail;
        private Bunifu.UI.WinForms.BunifuTextBox txtnom2;
        private System.Windows.Forms.CheckBox chbmdp;
    }
}